name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.14, 1.15, 1.16]
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.goVer }}
        id: go

      - name: Set up linters
        run: go get -u github.com/mgechev/revive

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: make install

      - name: Lint
        run: |
          make vet
          make lint
          make fmt
          git diff
          if [[ $(git diff) != '' ]]; then echo 'Invalid formatting!' >&2; exit 1; fi

      - name: Compile
        run: make compile